---
language: php

php:
  - 5.6
  - 7.0

install:
  - composer install

script:
  - php vendor/bin/phpcs --standard=psr2 --ignore=vendor -n .
  - php esc2text.php receipt-with-logo.bin
  - php exc2html.php receipt-with-logo.bin
